### PR TITLE
Added filtering

### PR DESCRIPTION
**Pull request by Daniil-Kienko**
Решил не писать кучу if в основном методе, а просто создать цепочку вызовов функции тк. в дальнейшем это упростит процесс добавления нового предиката. Передавал в функции весь объект, а не значение по которому идет фильтрация тк. в будущем нам может потребоваться добавление условий на основании других полей.
Группа --- Kh-051-.NET

### CODE REVIEW

**Comment by Daniil-Kienko** [comment]
If you are starting with something that has a .Length or .Count (such as ICollection<T>, IList<T>, List<T>, etc) - then this will be the fastest option, since it doesn't need to go through the GetEnumerator()/MoveNext()/Dispose() sequence required by Any() to check for a non-empty IEnumerable<T> sequence.

For just IEnumerable<T>, then Any() will generally be quicker, as it only has to look at one iteration. However, note that the LINQ-to-Objects implementation of Count() does check for ICollection<T> (using .Count as an optimisation) - so if your underlying data-source is directly a list/collection, there won't be a huge difference.

Of course, if you have used LINQ to filter it etc (Where etc), you will have an iterator-block based sequence, and so this ICollection<T> optimisation is useless.

In general with IEnumerable<T> : stick with Any() ;-p

From [StackOverflow](https://stackoverflow.com/questions/305092/which-method-performs-better-any-vs-count-0) )

> What advantage of `searchSettingsCollection.Genres.Count != 0` over `searchSettingsCollection.Genres.Any()`?

**Comment by Daniil-Kienko** [comment]
> The issue, I see here, that even when no filters passed into this class you still have 4 the same equivalent expressions `game => true`
> 
> But the whole idea of the task was to learn how to construct the expressions, which contain only those elements that useful
> 
> Task is done, however it could be implemented better. Good job, keep it up 👍

Do you think it was worth writing if statements in the main method, or are there any other methods to avoid this behavior?

**Comment by STeres-work** [comment]
> If you are starting with something that has a .Length or .Count (such as ICollection, IList, List, etc) - then this will be the fastest option, since it doesn't need to go through the GetEnumerator()/MoveNext()/Dispose() sequence required by Any() to check for a non-empty IEnumerable sequence.

Well, that's may be a valid point, however, in my opinion, a performance difference between `Any()` and `Count()` not really significant, but the code, that uses appropriate methods looks simpler and cleaner.

**Comment by STeres-work** [comment]
> Do you think it was worth writing if statements in the main method, or are there any other methods to avoid this behavior?

Yes, I have some thoughts on it, I will share them on the lecture

**Comment by Daniil-Kienko** [comment]
Thanks for review!
 I'll do my best in order to omit such kind of mistakes in my future works

**Pull request closed without merging**
